language: node_js
node_js: node

branches:
  except:
    - gh-pages

env:
  global:
    - DEPLOY_BRANCH="master"
    - SOURCE_DIR="public"
    - TARGET_BRANCH="gh-pages"
    - SSH_KEY="id_rsa"
    - GIT_NAME="RWEDA Bot"
    - GIT_EMAIL="rwedabot@redwoodeda.com"

before_install:
- openssl aes-256-cbc -K $encrypted_9625d8b4abbc_key -iv $encrypted_9625d8b4abbc_iv
  -in id_rsa.enc -out id_rsa -d

script:
  - node make.js
  - $(npm bin)/gh-pages-travis
